In [40]:
import numpy as np

**ARITHMETIC OPERATIONS**

In [26]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [27]:
a1+a2

array([ 6,  8, 10, 12])

In [28]:
a1-a2

array([-4, -4, -4, -4])

In [29]:
a1*a2

array([ 5, 12, 21, 32])

In [30]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [31]:
a2/a1

array([5.        , 3.        , 2.33333333, 2.        ])

In [32]:
a1//a2

array([0, 0, 0, 0])

In [33]:
a2//a1 #divide then remove decimal part (floor)

array([5, 3, 2, 2])

In [34]:
a1**a2  #a1 to the power a2

array([    1,    64,  2187, 65536])

In [35]:
a1*2

array([2, 4, 6, 8])

In [37]:
#l=[2,5,7,3]  #not possible in list
#l+10

In [38]:
arr=np.array(l)
arr

array([2, 5, 7, 3])

In [39]:
arr+10

array([12, 15, 17, 13])

In [41]:
arr1=np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

**Deep and Shallow copy**

In [43]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice = a[2:6]
slice

array([3, 4, 5, 6])

In [48]:
slice=slice*10
slice

array([300, 400, 500, 600])

In [49]:
a       #no change in original array upon change in slice --> shaqllow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
b=a
b[0]=66

In [52]:
a        #change in original array upon change in slice --> deep copy

array([66,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
b=a.copy()
b[0]=88

In [60]:
b

array([88,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
a

array([66,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Matrix Operation**

**Advance Array Manipulation**

In [ ]:
stacking

In [63]:
a1=np.array([1,2,3,4,5])
a2=np.array([9,8,7,6,0])

In [64]:
np.vstack((a1,a2))

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 0]])

In [65]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 9, 8, 7, 6, 0])

In [69]:
np.column_stack((a2,a1))

array([[9, 1],
       [8, 2],
       [7, 3],
       [6, 4],
       [0, 5]])

In [70]:
np.row_stack((a,b))

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4224\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[66,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [88,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
splitting arrays

In [72]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [74]:
np.hsplit(a,5)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21],
        [26]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25],
        [30]])]

In [75]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])]