In [2]:
import numpy as np

**numpy  indexing & slicing**

In [2]:
arr=np.arange(11,21)

In [3]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[0],arr[3]

(np.int64(11), np.int64(14))

**ARRAY SLICING**

In [5]:
arr[2:5]

array([13, 14, 15])

In [6]:
arr[:5
    ]

array([11, 12, 13, 14, 15])

In [7]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[2::2] #starts from index 2 goes till last by taking two jumps in each step

array([13, 15, 17, 19])

**MATRIX SLICING**

In [3]:
arr= np.arange(1,31).reshape(5,6)

In [4]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [5]:
arr[3,5]

np.int64(24)

In [7]:
arr[0:2,0:2]

array([[1, 2],
       [7, 8]])

In [10]:
arr[3:5,4:6]

array([[23, 24],
       [29, 30]])

**BOOLEAN INDEXING**

In [17]:
arr=np.arange(1,11)

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])