In [5]:
import numpy as np

In [ ]:
Basic Array Creation

In [7]:
np.array([1,2,3,4])  #array is not saved

array([1, 2, 3, 4])

In [8]:
arr=np.array([5,6,7,8])
arr   #after saving need to print separately

array([5, 6, 7, 8])

In [13]:
a = [2,5,3.7,"hello"] #list vcan have objects of multi data tyoe
a

[2, 5, 3.7, 'hello']

In [15]:
np.array(a) #array can have only one dta type, so here converted to data  type U32

array(['2', '5', '3.7', 'hello'], dtype='<U32')

In [16]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.array([[2,3,4],[6,7,8],[0,8,3]])

array([[2, 3, 4],
       [6, 7, 8],
       [0, 8, 3]])

In [ ]:
Array Generaration Function

In [23]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [29]:
arr = np.zeros((2,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.ones((5,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
arr = np.linspace(1,5,2)
arr    #returns element with linear or equa space (low,high,number of elements)

array([1., 5.])

In [36]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [37]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [38]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [ ]:
Random Generation Functio

In [40]:
np.random.rand(10) #returns 10 random number between 0 & 1

array([0.14293717, 0.94276644, 0.17249969, 0.51948634, 0.67925532,
       0.47336076, 0.39505053, 0.0132526 , 0.11080911, 0.46648498])

In [41]:
np.random.randn(15) #generates 15 numbers from a normal distribution with:

#Mean = 0

#Standard deviation = 1

array([ 0.04898313, -0.14075488, -1.09184614, -0.57114492, -0.6070686 ,
        0.96366986, -0.65310357,  1.50039912, -0.44815073, -0.13834072,
        0.95137954, -1.57339294, -0.93964903, -1.14564085,  0.89804941])

In [43]:
np.random.randint(6)#return a random integer between 0 & 6

5

In [44]:
np.random.randint(10,20,11)

array([10, 11, 12, 15, 14, 15, 12, 10, 15, 16, 10], dtype=int32)

**Array Attributes**

In [45]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.shape

(3, 3)

In [47]:
arr.size

9

In [48]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.min()

np.int64(1)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.sum()

np.int64(45)

In [54]:
np.sum(arr,1) #np.sum(array,axis) 0->vertical, 1->horizontal

array([ 6, 15, 24])

In [55]:
np.sum(arr,0)

array([12, 15, 18])

In [56]:
arr.std()#standard deviation

np.float64(2.581988897471611)

In [6]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [10]:
arr.resize((2,3), refcheck=False)
arr

array([[1, 2, 3],
       [4, 5, 6]])