In [11]:
import numpy as np

**Valid Sudoku**

In [12]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [13]:
#fsum of each row of a sodoku is samemoryview
b=np.sum(s,axis=1)

In [14]:
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [16]:
for i in b: 
    if i!=45:
        print("invalid sudoku")
        break
else: print("valid row sudoku")

valid row sudoku


In [18]:
c=np.sum(s,axis=0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [19]:
for i in c: 
    if i!=45:
        print("invalid sudoku")
        break
else: print("valid column sudoku")

valid column sudoku


In [22]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


**validated**

**General Questions**

In [73]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [47]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [48]:
#Find the average age of students.
np.mean(data[:,0]) #select row, select column

np.float64(18.4)

In [49]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [50]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [53]:
#Get details of the student who scored more than 90 in Math.
for i in range(1,5):
    if data[i,1]>90:
        print(data[i,:])
    

[19 92 88]


In [55]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [61]:
#Increase Math marks of all students by 5.abs
data[:,1]=data[:,1] + 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [63]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [64]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [66]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [71]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])

In [74]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [75]:
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])